fix version check issue in draft-new-release workflow

diff --git a/workflow-templates/basic/.github/workflows/draft-new-release.yaml b/workflow-templates/basic/.github/workflows/draft-new-release.yaml
--- a/workflow-templates/basic/.github/workflows/draft-new-release.yaml
+++ b/workflow-templates/basic/.github/workflows/draft-new-release.yaml
@@ -22,19 +22,9 @@ jobs:
         shell: bash -l {0}  # We want to use bash shell all the time, Conda is picky
 
     steps:
-    - name: Validate input
-      id: validate-input
+    - name: Validate release type input
+      id: validate-release
       run: |
-        # Check if input version is in correct format
-        if [[ ! ${{ github.event.inputs.version }} =~ v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "::error::Invalid input version: wrong format!"
-          exit 1
-        fi
-        # Check if input version already exists as git tag
-        if [[ ! -z $(git tag | grep ${{ github.event.inputs.version }}) ]]; then
-          echo "::error::Invalid input version: it already exists!"
-          exit 1
-        fi
         # Check if input release-type is in correct format
         if [[ ! ${{ github.event.inputs.release-type }} = "release" ]] && \
            [[ ! ${{ github.event.inputs.release-type }} = "hotfix" ]]; then
@@ -53,6 +43,21 @@ jobs:
       uses: actions/checkout@v2
       with:
         ref: ${{ env.branch_from }}
+        fetch-depth: 0    # Fetch history for all branches and tags
+
+    - name: Validate version input
+      id: validate-input
+      run: |
+        # Check if input version is in correct format
+        if [[ ! ${{ github.event.inputs.version }} =~ v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "::error::Invalid input version: wrong format!"
+          exit 1
+        fi
+        # Check if input version already exists as git tag
+        if [[ ! -z $(git tag | grep ${{ github.event.inputs.version }}) ]]; then
+          echo "::error::Invalid input version: it already exists!"
+          exit 1
+        fi
 
     - name: Create release branch
       run: git checkout -b ${{ github.event.inputs.release-type }}/${{ github.event.inputs.version }}
